/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BytesLike, CallOverrides, ContractTransaction, Overrides, PopulatedTransaction, Signer, utils } from 'ethers';
import { FunctionFragment, Result } from '@ethersproject/abi';
import { Listener, Provider } from '@ethersproject/providers';
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface IMachineryInterface extends utils.Interface {
  contractName: 'IMachinery';
  functions: {
    'isMechanic(address)': FunctionFragment;
    'mechanicsRegistry()': FunctionFragment;
    'setMechanicsRegistry(address)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'isMechanic', values: [string]): string;
  encodeFunctionData(functionFragment: 'mechanicsRegistry', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setMechanicsRegistry', values: [string]): string;

  decodeFunctionResult(functionFragment: 'isMechanic', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mechanicsRegistry', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setMechanicsRegistry', data: BytesLike): Result;

  events: {};
}

export interface IMachinery extends BaseContract {
  contractName: 'IMachinery';
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMachineryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isMechanic(mechanic: string, overrides?: CallOverrides): Promise<[boolean] & { _isMechanic: boolean }>;

    mechanicsRegistry(overrides?: CallOverrides): Promise<[string] & { _mechanicsRegistry: string }>;

    setMechanicsRegistry(_mechanicsRegistry: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;
  };

  isMechanic(mechanic: string, overrides?: CallOverrides): Promise<boolean>;

  mechanicsRegistry(overrides?: CallOverrides): Promise<string>;

  setMechanicsRegistry(_mechanicsRegistry: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  callStatic: {
    isMechanic(mechanic: string, overrides?: CallOverrides): Promise<boolean>;

    mechanicsRegistry(overrides?: CallOverrides): Promise<string>;

    setMechanicsRegistry(_mechanicsRegistry: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    isMechanic(mechanic: string, overrides?: CallOverrides): Promise<BigNumber>;

    mechanicsRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    setMechanicsRegistry(_mechanicsRegistry: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    isMechanic(mechanic: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mechanicsRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMechanicsRegistry(_mechanicsRegistry: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;
  };
}
