/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BytesLike, CallOverrides, ContractTransaction, Overrides, PopulatedTransaction, Signer, utils } from 'ethers';
import { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import { Listener, Provider } from '@ethersproject/providers';
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface ISwapperInterface extends utils.Interface {
  contractName: 'ISwapper';
  functions: {
    'SWAPPER_TYPE()': FunctionFragment;
    'setTradeFactory(address)': FunctionFragment;
    'tradeFactory()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'SWAPPER_TYPE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setTradeFactory', values: [string]): string;
  encodeFunctionData(functionFragment: 'tradeFactory', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'SWAPPER_TYPE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setTradeFactory', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'tradeFactory', data: BytesLike): Result;

  events: {
    'TradeFactorySet(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'TradeFactorySet'): EventFragment;
}

export type TradeFactorySetEvent = TypedEvent<[string], { _tradeFactory: string }>;

export type TradeFactorySetEventFilter = TypedEventFilter<TradeFactorySetEvent>;

export interface ISwapper extends BaseContract {
  contractName: 'ISwapper';
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISwapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SWAPPER_TYPE(overrides?: CallOverrides): Promise<[number]>;

    setTradeFactory(_tradeFactory: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    tradeFactory(overrides?: CallOverrides): Promise<[string]>;
  };

  SWAPPER_TYPE(overrides?: CallOverrides): Promise<number>;

  setTradeFactory(_tradeFactory: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  tradeFactory(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SWAPPER_TYPE(overrides?: CallOverrides): Promise<number>;

    setTradeFactory(_tradeFactory: string, overrides?: CallOverrides): Promise<void>;

    tradeFactory(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    'TradeFactorySet(address)'(_tradeFactory?: null): TradeFactorySetEventFilter;
    TradeFactorySet(_tradeFactory?: null): TradeFactorySetEventFilter;
  };

  estimateGas: {
    SWAPPER_TYPE(overrides?: CallOverrides): Promise<BigNumber>;

    setTradeFactory(_tradeFactory: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    tradeFactory(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SWAPPER_TYPE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setTradeFactory(_tradeFactory: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    tradeFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
