/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import { Provider, TransactionRequest } from '@ethersproject/providers';
import type { CommonErrors, CommonErrorsInterface } from '../CommonErrors';

const _abi = [
  {
    inputs: [],
    name: 'IncorrectSwapInformation',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotAuthorized',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroSlippage',
    type: 'error',
  },
];

const _bytecode =
  '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204de61c444e198d09fd78e04e218fae5b830df7582fa5323e5a537a3adf63068c64736f6c63430008090033';

type CommonErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (xs: CommonErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CommonErrors__factory extends ContractFactory {
  constructor(...args: CommonErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = 'CommonErrors';
  }

  deploy(overrides?: Overrides & { from?: string | Promise<string> }): Promise<CommonErrors> {
    return super.deploy(overrides || {}) as Promise<CommonErrors>;
  }
  getDeployTransaction(overrides?: Overrides & { from?: string | Promise<string> }): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CommonErrors {
    return super.attach(address) as CommonErrors;
  }
  connect(signer: Signer): CommonErrors__factory {
    return super.connect(signer) as CommonErrors__factory;
  }
  static readonly contractName: 'CommonErrors';
  public readonly contractName: 'CommonErrors';
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CommonErrorsInterface {
    return new utils.Interface(_abi) as CommonErrorsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): CommonErrors {
    return new Contract(address, _abi, signerOrProvider) as CommonErrors;
  }
}
