/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { IAggregationExecutor, IAggregationExecutorInterface } from '../IAggregationExecutor';

const _abi = [
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'data',
        type: 'bytes',
      },
    ],
    name: 'callBytes',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
];

export class IAggregationExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IAggregationExecutorInterface {
    return new utils.Interface(_abi) as IAggregationExecutorInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAggregationExecutor {
    return new Contract(address, _abi, signerOrProvider) as IAggregationExecutor;
  }
}
